version: '3'

services:
  dev:
    container_name: Cpp_dev

    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile


    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    volumes:
      - ..:/workspace:cached
    
    working_dir: /workspace

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    tty: true
    stdin_open: true
    command: sleep infinity


